### ISSUE TITLE
libgbm integration

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/feathers-deprecated#3]
Goal: communicate with the linux kernel using gbm, to evntually present an image.

**Comment by Gaspard--** [comment]
I believe the gbm.h file (of which I found [this mirror](https://github.com/robclark/libgbm/blob/master/gbm.h) on github) which is located at `/usr/include/gbm.h` may be of interrest.
I think reading from it, you prbably have to create a device.
 ```c
 /**
    * Buffer is going to be presented to the screen using an API such as KMS
    */
   GBM_BO_USE_SCANOUT      = (1 << 0),
```
seems to imply we must use KMS. Going read about that and report back.

**Comment by Gaspard--** [comment]
I think @Arignir might know a thing or two about kernel mode setting.

**Comment by Gaspard--** [comment]
Interresting link: http://moi.vonos.net/linux/drm-and-kms/

**Comment by Arignir** [comment]
Not that much, actually. I only know what Wikipedia says: it's a procedure to let the kernel handle display mode. I've never dig into that before.

The reading that you provide is very interesting, and goes way beyond what i knew before.
Maybe a complement could be (French): [this article](http://www.planet-libre.org/index.php?post_id=3195).

**Comment by Gaspard--** [comment]
@davidzeng8 seeing how you have a hard time advancing, I think it may be time to fall back to using EGL to blit a buffer (that we will fill with vulkan) to the screen. It may not be optimal, but we have to move forwards.

**Comment by Zeng-Zer** [comment]
I agree, better keep moving on than struggling.
